#URL
url: https://qiaoxianshen.github.io
baseurl: /


#博客名字和描述自定义
title: Newton
description: 基于jekyll的github极简主题

#个人信息
author: qiaoxianshen
github: qiaoxianshen
email:  *@foxmail.com

#下面的是配置和插件，不需要改
permalink: none
plugins: [jekyll-sitemap]
